include:
  - /cron/bains-douches/jobs/socialgouv.yml

.bathing:
  extends:
    - .cron_rules
  image: alpine:3.15.3
  before_script:
    - apk add bash git parallel
  script:
    - git clone https://github.com/SocialGouv/${name}.git ${CI_BUILDS_DIR}/${name}
    - cd ${CI_BUILDS_DIR}/${name}
    - git remote add gitlab.factory.social.gouv https://SocialGroovyBot:${SOCIALGROOVYBOT_GITLAB_TOKEN}@gitlab.factory.social.gouv.fr/SocialGouv/${name}.git
    - ${CI_PROJECT_DIR}/maintenance/tools/git-mirror-cleaner/bin/git-mirror-cleaner origin gitlab.factory.social.gouv

Sync SocialGouv group jobs:
  extends:
    - .cron_rules
  image: alpine:3.15.3
  allow_failure: true
  variables:
    GIT_AUTHOR_EMAIL: 45039513+SocialGroovyBot@users.noreply.github.com
    GIT_AUTHOR_NAME: Social Groovy Bot
    GIT_COMMITTER_EMAIL: ${GIT_AUTHOR_EMAIL}
    GIT_COMMITTER_NAME: ${GIT_AUTHOR_NAME}
    GIT_STRATEGY: clone
    GITLAB_API_TOKEN: ${SOCIALGROOVYBOT_GITLAB_API_TOKEN}
  before_script:
    - apk add bash jq git

    # Install laster yq version
    # see https://github.com/mikefarah/yq/issues/190#issuecomment-621512382
    - wget -q -O /usr/bin/yq
      $(
        wget -q -O - https://api.github.com/repos/mikefarah/yq/releases/latest |
        jq -r '.assets[] |
        select(.name == "yq_linux_amd64") |
        .browser_download_url'
      )
    - chmod +x /usr/bin/yq

    # Smoke test
    - jq --version
    - yq --version
  script:
    - git checkout ${CI_COMMIT_REF_NAME}
    - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CI_PROJECT_PATH}.git
    - cron/bains-douches/bin/bathing SocialGouv > cron/bains-douches/jobs/socialgouv.yml
    - git add cron/bains-douches/jobs/socialgouv.yml
    - "git commit -m 'feat(bains-douches): sync jobs/socialgouv.yml'"
    - git push origin ${CI_COMMIT_REF_NAME}

