Test git-mirror-cleaner:
  extends:
    - .default_rules
  image: ghcr.io/socialgouv/docker/bats:6.43.2
  variables:
    GIT_STRATEGY: clone
  before_script:
    - apk add parallel
  script:
    - cd maintenance/tools/git-mirror-cleaner
    - bats -t test
