Lint git-mirror-cleaner:
  extends:
    - .default_rules
  image: koalaman/shellcheck-alpine:v0.7.1
  script:
    - shellcheck ./maintenance/tools/git-mirror-cleaner/bin/git-mirror-cleaner

Test git-mirror-cleaner:
  extends:
    - .default_rules
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/bats:1.22.2
  variables:
    GIT_STRATEGY: clone
  before_script:
    - apk add parallel
  script:
    - cd maintenance/tools/git-mirror-cleaner
    - bats -t test
