Test git-mirror-cleaner:
  extends:
    - .default_rules
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/bats:1.60.0
  variables:
    GIT_STRATEGY: clone
  before_script:
    - apk add parallel
  script:
    - cd maintenance/tools/git-mirror-cleaner
    - bats -t test
