name: Review

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - v*

jobs:
  register-app:
    name: Build & Register app
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: dev
          imageName: GITHUB_REPO_NAME/app
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy review branch
    runs-on: ubuntu-latest
    needs: [register-app]
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/kube-workflow@master
        with:
          environment: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}